version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 8001:5432
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8080
    environment:
      SYNC_KEY: abcdefg
      NODE_ENV: development
