on: push

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: docker build -t app . --file Dockerfile

    - name: Log in to the registry and push
      run: 
        export CR_PAT=${{secrets.TOKEN}} \
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin \
        docker push ghcr.io/cornflowerblu/app:testing
    
  create-services-and-test:
    runs-on: ubuntu-latest
    needs: build-app
    services:
    # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      app:
        image: ghcr.io/cornflowerblu/app:testing
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v3

      - name: Install Deps
        run: npm ci --no-audit

      - name: Run Tests
        run: npm run test
