on: push

jobs:
  setup-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: docker build -t app . --file Dockerfile
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    
    services:
    # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      app:
        image: app
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 80:8080
  
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: services

      - name: Install Deps
        run: npm ci --no-audit

      - name: Run Tests
        run: npm run test
