on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}    
    
    - name: Install modules
      run: npm ci --no-audit
    
    - name: Run tests
      run: npm run test