on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        port: 8000
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test