on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
    # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: docker build -t app . --file Dockerfile
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        PORT: 8000
    
    - name: Run App
      run: docker run app -d
    
    - name: Install modules
      run: npm ci --no-audit
    
    - name: Build & Test the app
      run: npm run test
