on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Install modules
      run: npm ci --no-audit
    
    - name: Build & Run the app
      run: npm run build && npm start

    - name: Run tests
      run: npm run test:ci